version: '3.8'

services:
  # FastAPI Backend (simplified for development)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.simple
    container_name: paimons-api
    environment:
      - PYTHONPATH=/app
      - ORACLE_SKIP=true
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./dal:/app/dal
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: paimons-ui
    environment:
      - REACT_APP_API_URL=http://api:8000
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm start


  # Simple reverse proxy with nginx (lighter than Caddy for dev)
  nginx:
    image: nginx:alpine
    container_name: paimons-nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - ui
    restart: unless-stopped

volumes: