version: '3.8'

services:
  # Oracle Database 23ai
  oracle-db:
    image: container-registry.oracle.com/database/free:23.5.0.0-lite
    container_name: paimons-oracle
    environment:
      - ORACLE_PWD=OraclePassword123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./config/oracle:/opt/oracle/scripts/startup
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -S sys/OraclePassword123@//localhost:1521/FREEPDB1 as sysdba | grep -q '^1$'"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 120s
    restart: unless-stopped

  # FastAPI Backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: paimons-api
    depends_on:
      - minio
    environment:
      - ORACLE_USER=paimons_user
      - ORACLE_PASSWORD=password123
      - ORACLE_DSN=oracle-db:1521/FREEPDB1
      - PYTHONPATH=/app
      - ORACLE_SKIP=true
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=paimons
      - MINIO_SECRET_KEY=paimons123
      - MINIO_BUCKET_NAME=codex
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./api:/app
      - ./dal:/app/dal
    # depends_on:
    #   oracle-db:
    #     condition: service_healthy
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: paimons-ui
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - BROWSER=none
      - FAST_REFRESH=false
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm start

  # Caddy Reverse Proxy
  caddy:
    image: caddy:2.7-alpine
    container_name: paimons-caddy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
      - ui
    restart: unless-stopped


  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: paimons-minio
    environment:
      - MINIO_ROOT_USER=paimons
      - MINIO_ROOT_PASSWORD=paimons123
      - MINIO_CONSOLE_ADDRESS=:9001
    ports:
      - "127.0.0.1:9000:9000"  # MinIO API
      - "127.0.0.1:9001:9001"  # MinIO Console (Web UI)
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  oracle_data:
  caddy_data:
  caddy_config:
  minio_data: